name: Publish Version Info

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    name: Publish Version Info on License Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git

      - name: Push version info
        env:
          CI_PIPELINE_ID: ${{ github.run_number }}
        run: |
          TAG="${{ inputs.version }}"
          if [[ "$TAG" == *"-rc" ]]; then
              CHANNEL="rc"
          elif [[ "$TAG" == *"-stable" ]]; then
              CHANNEL="stable"
          else
              CHANNEL="unknown"
          fi

          NOTES=$(git log -1 --pretty=%f)
          JSON_PAYLOAD="{ \"app\": \"backend\", \"version\": \"$TAG\", \"build_number\": ${CI_PIPELINE_ID}, \"notes\": \"$NOTES\", \"channel\": \"$CHANNEL\" }"
          echo "Sending: $JSON_PAYLOAD"
          status_code=$(curl -o /dev/null -s -w "%{http_code}" -X POST https://license.finmars.com/api/v1/version/ -H "Content-Type: application/json" -d "$JSON_PAYLOAD")

          if [[ "$status_code" -ne "201" ]]; then
            echo "Publish version failed, http status: $status_code"
            exit 6
          fi

          echo "Publish version succeeded."
